/**
 * Complete API Endpoint Documentation
 *
 * Auto-generated from user-routes.ts analysis
 * All 121 endpoints documented with full details
 */

import type { APIEndpointDoc } from './ai-types';

export const FULL_API_ENDPOINTS: APIEndpointDoc[] = [
  // ============================================================================
  // HEALTH & SYSTEM
  // ============================================================================
  {
    method: 'GET',
    path: '/api/health',
    description: 'Health check endpoint to verify API is running',
    authentication: 'none',
    responseBody: { type: '{ status: string, timestamp: string, version: string }', description: 'Health status' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 53,
  },

  // ============================================================================
  // PAYMENT & STRIPE
  // ============================================================================
  {
    method: 'POST',
    path: '/api/create-payment-intent',
    description: 'Create Stripe PaymentIntent for enrollment fee ($28)',
    authentication: 'user',
    requestBody: {
      type: 'CreatePaymentIntentRequest',
      description: 'Payment details',
      fields: [
        { name: 'amount', type: 'number', required: true, description: 'Amount in cents (2800 = $28)' },
        { name: 'idempotencyKey', type: 'string', required: false, description: 'Unique key to prevent duplicate charges' },
        { name: 'metadata', type: 'object', required: false, description: 'User info for Stripe dashboard' },
      ],
    },
    responseBody: { type: '{ clientSecret: string }', description: 'Stripe client secret for frontend' },
    errorCodes: [
      { code: 500, message: 'Payment processing not configured', description: 'STRIPE_SECRET_KEY missing' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 61,
  },
  {
    method: 'POST',
    path: '/api/validate-coupon',
    description: 'Validate a discount coupon code',
    authentication: 'user',
    requestBody: {
      type: 'ValidateCouponRequest',
      description: 'Coupon to validate',
      fields: [
        { name: 'code', type: 'string', required: true, description: 'Coupon code to check' },
      ],
    },
    responseBody: { type: '{ valid: boolean, discount?: number, message?: string }', description: 'Validation result' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 153,
  },
  {
    method: 'GET',
    path: '/api/admin/stripe/payments',
    description: 'List all Stripe payments with customer details',
    authentication: 'admin',
    responseBody: { type: 'StripePayment[]', description: 'Recent payments from Stripe' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2585,
  },
  {
    method: 'POST',
    path: '/api/admin/stripe/link',
    description: 'Link a Stripe payment to a user account',
    authentication: 'admin',
    requestBody: {
      type: 'LinkPaymentRequest',
      description: 'Payment linking details',
      fields: [
        { name: 'paymentIntentId', type: 'string', required: true, description: 'Stripe PaymentIntent ID' },
        { name: 'userId', type: 'string', required: true, description: 'User to link payment to' },
      ],
    },
    responseBody: { type: '{ success: boolean }', description: 'Link result' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2704,
  },

  // ============================================================================
  // DATABASE MAINTENANCE & INDEXING
  // ============================================================================
  {
    method: 'POST',
    path: '/api/admin/backfill-indexes',
    description: 'Admin tool to rebuild secondary indexes for optimized queries. Backfills phone mappings, enrollment indexes, daily score indexes, and points ledger indexes. Use when indexes are out of sync or after data migrations.',
    authentication: 'admin',
    requestBody: {
      type: 'BackfillIndexesRequest',
      description: 'Backfill configuration (query params)',
      fields: [
        { name: 'type', type: 'string', required: false, description: 'Index type to backfill: "phones", "enrollments", "scores", "points", or "all" (default)' },
        { name: 'limit', type: 'number', required: false, description: 'Max records to process per batch (default: 100, max: 200)' },
        { name: 'offset', type: 'number', required: false, description: 'Starting offset for pagination (default: 0)' },
      ],
    },
    responseBody: {
      type: '{ type: string, limit: number, offset: number, enrollments: IndexResult, dailyScores: IndexResult, phoneMappings: IndexResult, pointsLedger: IndexResult, errors: string[] }',
      description: 'Backfill results showing processed/indexed counts per type and any errors'
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2617,
  },

  // ============================================================================
  // REGISTRATION & AUTH
  // ============================================================================
  {
    method: 'POST',
    path: '/api/register',
    description: 'Register a new user account',
    authentication: 'none',
    requestBody: {
      type: 'RegisterRequest',
      description: 'New user details',
      fields: [
        { name: 'name', type: 'string', required: true, description: 'Display name' },
        { name: 'email', type: 'string', required: true, description: 'Email address' },
        { name: 'phone', type: 'string', required: true, description: 'Phone in E.164 format' },
        { name: 'role', type: 'string', required: true, description: 'participant | coach' },
        { name: 'referralCode', type: 'string', required: false, description: 'Referrer code' },
      ],
    },
    responseBody: { type: 'User', description: 'Created user' },
    errorCodes: [
      { code: 400, message: 'Invalid data', description: 'Missing required fields' },
      { code: 409, message: 'User exists', description: 'Phone/email already registered' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 184,
  },
  {
    method: 'POST',
    path: '/api/login',
    description: 'Legacy login endpoint (use OTP flow instead)',
    authentication: 'none',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1173,
  },
  {
    method: 'POST',
    path: '/api/auth/send-otp',
    description: 'Send OTP code via SMS to phone number',
    authentication: 'none',
    requestBody: {
      type: 'SendOtpRequest',
      description: 'Phone to send OTP',
      fields: [
        { name: 'phone', type: 'string', required: true, description: 'Phone in E.164 format (+1XXXXXXXXXX)' },
      ],
    },
    responseBody: { type: '{ success: boolean, expiresAt: number }', description: 'Send result' },
    errorCodes: [
      { code: 400, message: 'Invalid phone', description: 'Phone format invalid' },
      { code: 429, message: 'Rate limited', description: 'Too many OTP requests' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1214,
  },
  {
    method: 'POST',
    path: '/api/auth/verify-otp',
    description: 'Verify OTP code and authenticate user',
    authentication: 'none',
    requestBody: {
      type: 'VerifyOtpRequest',
      description: 'OTP verification',
      fields: [
        { name: 'phone', type: 'string', required: true, description: 'Phone in E.164 format' },
        { name: 'code', type: 'string', required: true, description: '6-digit OTP code' },
      ],
    },
    responseBody: { type: '{ user?: User, isNewUser?: boolean }', description: 'Auth result' },
    errorCodes: [
      { code: 401, message: 'Invalid code', description: 'Wrong OTP code' },
      { code: 401, message: 'Code expired', description: 'OTP older than 10 minutes' },
      { code: 429, message: 'Max attempts', description: '5+ failed attempts' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1296,
  },
  {
    method: 'GET',
    path: '/api/auth/check-verified/:phone',
    description: 'Check if phone number is verified',
    authentication: 'none',
    responseBody: { type: '{ verified: boolean, user?: User }', description: 'Verification status' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1374,
  },

  // ============================================================================
  // USER PROFILE
  // ============================================================================
  {
    method: 'GET',
    path: '/api/me',
    description: 'Get current authenticated user profile',
    authentication: 'user',
    responseBody: { type: 'User', description: 'Current user with enrollments' },
    errorCodes: [
      { code: 401, message: 'Unauthorized', description: 'Not authenticated' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 509,
  },
  {
    method: 'PATCH',
    path: '/api/users/me',
    description: 'Update current user profile',
    authentication: 'user',
    requestBody: {
      type: 'UpdateProfileRequest',
      description: 'Fields to update',
      fields: [
        { name: 'name', type: 'string', required: false, description: 'Display name' },
        { name: 'email', type: 'string', required: false, description: 'Email address' },
        { name: 'avatarUrl', type: 'string', required: false, description: 'Profile photo URL' },
        { name: 'hasScale', type: 'boolean', required: false, description: 'User has smart scale' },
      ],
    },
    responseBody: { type: 'User', description: 'Updated user' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 523,
  },
  {
    method: 'GET',
    path: '/api/users/:coachId/coach-info',
    description: 'Get public coach info for referral display',
    authentication: 'user',
    responseBody: { type: '{ name: string, avatarUrl?: string }', description: 'Coach public info' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 611,
  },
  {
    method: 'POST',
    path: '/api/users/me/pwa-analytics',
    description: 'Track PWA install/usage analytics',
    authentication: 'user',
    requestBody: {
      type: 'PWAAnalyticsRequest',
      description: 'PWA event data',
      fields: [
        { name: 'event', type: 'string', required: true, description: 'Event type (install, dismiss, etc)' },
        { name: 'source', type: 'string', required: false, description: 'Where event triggered from' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 633,
  },

  // ============================================================================
  // DAILY SCORES (HABITS)
  // ============================================================================
  {
    method: 'GET',
    path: '/api/scores',
    description: 'Get daily habit scores for current project',
    authentication: 'user',
    responseBody: { type: 'DailyScore[]', description: 'All daily scores' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 683,
  },
  {
    method: 'POST',
    path: '/api/scores',
    description: 'Submit or update daily habit score',
    authentication: 'user',
    requestBody: {
      type: 'DailyScoreUpdate',
      description: 'Habit completions',
      fields: [
        { name: 'date', type: 'string', required: true, description: 'Date in YYYY-MM-DD format' },
        { name: 'water', type: 'boolean', required: false, description: 'Water goal completed' },
        { name: 'steps', type: 'boolean', required: false, description: 'Steps goal completed' },
        { name: 'sleep', type: 'boolean', required: false, description: 'Sleep goal completed' },
        { name: 'lesson', type: 'boolean', required: false, description: 'Daily lesson completed' },
      ],
    },
    responseBody: { type: 'DailyScore', description: 'Updated score with points' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 701,
  },
  {
    method: 'GET',
    path: '/api/scores/history',
    description: 'Get historical daily scores with stats',
    authentication: 'user',
    responseBody: { type: '{ scores: DailyScore[], stats: ScoreStats }', description: 'History with stats' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 894,
  },

  // ============================================================================
  // BIOMETRICS
  // ============================================================================
  {
    method: 'GET',
    path: '/api/biometrics/history',
    description: 'Get all biometric submissions for user',
    authentication: 'user',
    responseBody: { type: 'WeeklyBiometric[]', description: 'Week 0-4 submissions' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 774,
  },
  {
    method: 'GET',
    path: '/api/biometrics/:weekNumber',
    description: 'Get biometric submission for specific week',
    authentication: 'user',
    responseBody: { type: 'WeeklyBiometric | null', description: 'Week submission or null' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 804,
  },
  {
    method: 'POST',
    path: '/api/biometrics',
    description: 'Submit weekly biometric data with scale photo',
    authentication: 'user',
    requestBody: {
      type: 'BiometricSubmission',
      description: 'Weekly measurements',
      fields: [
        { name: 'weekNumber', type: 'number', required: true, description: 'Week 0-4' },
        { name: 'weight', type: 'number', required: true, description: 'Weight in lbs' },
        { name: 'bodyFat', type: 'number', required: false, description: 'Body fat percentage' },
        { name: 'visceralFat', type: 'number', required: false, description: 'Visceral fat level' },
        { name: 'leanMass', type: 'number', required: false, description: 'Lean mass in lbs' },
        { name: 'metabolicAge', type: 'number', required: false, description: 'Metabolic age' },
        { name: 'screenshotUrl', type: 'string', required: true, description: 'Scale photo R2 URL' },
      ],
    },
    responseBody: { type: 'WeeklyBiometric', description: 'Created submission' },
    errorCodes: [
      { code: 400, message: 'Invalid week', description: 'Week must be 0-4' },
      { code: 409, message: 'Already submitted', description: 'Week already has submission' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 822,
  },

  // ============================================================================
  // REFERRALS & ROSTER
  // ============================================================================
  {
    method: 'GET',
    path: '/api/referrals/history',
    description: 'Get referral history for coach',
    authentication: 'user',
    responseBody: { type: 'ReferralLedger[]', description: 'Referral transactions' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 926,
  },
  {
    method: 'GET',
    path: '/api/roster',
    description: 'Get team roster for coach/group leader',
    authentication: 'user',
    responseBody: { type: 'RosterMember[]', description: 'Team members with stats' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1006,
  },
  {
    method: 'GET',
    path: '/api/roster/:recruitId/biometrics',
    description: 'Get biometrics for a team member (coach view)',
    authentication: 'user',
    responseBody: { type: 'WeeklyBiometric[]', description: 'Recruit biometrics' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1039,
  },
  {
    method: 'GET',
    path: '/api/group-leaders',
    description: 'Get list of all group leaders (facilitators/coaches). Returns users with role=facilitator or role=coach who can lead participant groups.',
    authentication: 'user',
    responseBody: { type: 'GroupLeader[]', description: 'All group leaders with their stats' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1128,
  },
  {
    method: 'GET',
    path: '/api/captains',
    description: '@deprecated - Use /api/group-leaders instead. Legacy endpoint for backwards compatibility.',
    authentication: 'user',
    responseBody: { type: 'GroupLeader[]', description: 'All group leaders (legacy alias)' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1131,
  },
  {
    method: 'POST',
    path: '/api/orphan/assign',
    description: 'Assign orphan user to a captain',
    authentication: 'user',
    requestBody: {
      type: 'AssignOrphanRequest',
      description: 'Assignment details',
      fields: [
        { name: 'userId', type: 'string', required: true, description: 'Orphan user ID' },
        { name: 'captainId', type: 'string', required: true, description: 'Captain to assign to' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1116,
  },
  {
    method: 'GET',
    path: '/api/referrer/:code',
    description: 'Get referrer info by referral code',
    authentication: 'none',
    responseBody: { type: '{ name: string, avatarUrl?: string }', description: 'Referrer public info' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1401,
  },

  // ============================================================================
  // LEADS (QUIZ LEADS)
  // ============================================================================
  {
    method: 'POST',
    path: '/api/leads',
    description: 'Submit a quiz lead (potential customer)',
    authentication: 'none',
    requestBody: {
      type: 'CreateLeadRequest',
      description: 'Lead info from quiz',
      fields: [
        { name: 'name', type: 'string', required: true, description: 'Lead name' },
        { name: 'email', type: 'string', required: true, description: 'Lead email' },
        { name: 'phone', type: 'string', required: false, description: 'Lead phone' },
        { name: 'referralCode', type: 'string', required: false, description: 'Coach referral code' },
        { name: 'quizAnswers', type: 'object', required: false, description: 'Quiz responses' },
      ],
    },
    responseBody: { type: 'QuizLead', description: 'Created lead' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1424,
  },
  {
    method: 'GET',
    path: '/api/leads',
    description: 'Get leads for coach dashboard',
    authentication: 'user',
    responseBody: { type: 'QuizLead[]', description: 'Coach leads' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1533,
  },
  {
    method: 'PATCH',
    path: '/api/leads/:leadId/convert',
    description: 'Mark lead as converted to customer',
    authentication: 'user',
    responseBody: { type: 'QuizLead', description: 'Updated lead' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1575,
  },

  // ============================================================================
  // STATS & ANALYTICS
  // ============================================================================
  {
    method: 'GET',
    path: '/api/stats',
    description: 'Get system-wide statistics',
    authentication: 'user',
    responseBody: { type: 'SystemStats', description: 'Platform stats' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1139,
  },
  {
    method: 'GET',
    path: '/api/avatars/recent',
    description: 'Get recent user avatars for social proof',
    authentication: 'none',
    responseBody: { type: 'string[]', description: 'Recent avatar URLs' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1151,
  },

  // ============================================================================
  // ADMIN: USERS
  // ============================================================================
  {
    method: 'GET',
    path: '/api/admin/users',
    description: 'Get all users with filters',
    authentication: 'admin',
    responseBody: { type: 'User[]', description: 'All users' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1611,
  },
  {
    method: 'GET',
    path: '/api/admin/users/:userId',
    description: 'Get specific user details',
    authentication: 'admin',
    responseBody: { type: 'User', description: 'User details' },
    errorCodes: [
      { code: 404, message: 'Not found', description: 'User does not exist' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1637,
  },
  {
    method: 'PATCH',
    path: '/api/admin/users/:userId',
    description: 'Update user details (admin)',
    authentication: 'admin',
    requestBody: {
      type: 'AdminUpdateUserRequest',
      description: 'Fields to update',
      fields: [
        { name: 'name', type: 'string', required: false, description: 'Display name' },
        { name: 'email', type: 'string', required: false, description: 'Email address' },
        { name: 'phone', type: 'string', required: false, description: 'Phone number' },
        { name: 'isAdmin', type: 'boolean', required: false, description: 'Admin status' },
        { name: 'isGroupLeader', type: 'boolean', required: false, description: 'Coach status' },
      ],
    },
    responseBody: { type: 'User', description: 'Updated user' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1663,
  },
  {
    method: 'DELETE',
    path: '/api/admin/users/:userId',
    description: 'Soft-delete a user',
    authentication: 'admin',
    responseBody: { type: '{ success: boolean }', description: 'Deletion result' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1777,
  },
  {
    method: 'POST',
    path: '/api/admin/users/:userId/restore',
    description: 'Restore a soft-deleted user',
    authentication: 'admin',
    responseBody: { type: 'User', description: 'Restored user' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1831,
  },
  {
    method: 'GET',
    path: '/api/admin/users/deleted/list',
    description: 'Get list of soft-deleted users',
    authentication: 'admin',
    responseBody: { type: 'User[]', description: 'Deleted users' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1884,
  },
  {
    method: 'DELETE',
    path: '/api/admin/users/:userId/permanent',
    description: 'Permanently delete a user (no recovery)',
    authentication: 'admin',
    responseBody: { type: '{ success: boolean }', description: 'Deletion result' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1921,
  },
  {
    method: 'POST',
    path: '/api/admin/users/merge',
    description: 'Merge duplicate user accounts',
    authentication: 'admin',
    requestBody: {
      type: 'MergeUsersRequest',
      description: 'Merge details',
      fields: [
        { name: 'primaryUserId', type: 'string', required: true, description: 'User to keep' },
        { name: 'duplicateUserId', type: 'string', required: true, description: 'User to merge in' },
      ],
    },
    responseBody: { type: 'User', description: 'Merged user' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 1974,
  },
  {
    method: 'GET',
    path: '/api/admin/duplicates',
    description: 'Find potential duplicate users',
    authentication: 'admin',
    responseBody: { type: 'DuplicateGroup[]', description: 'Duplicate clusters' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2249,
  },
  {
    method: 'GET',
    path: '/api/debug/duplicates-test',
    description: 'Debug endpoint for duplicate detection',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2192,
  },
  {
    method: 'GET',
    path: '/api/admin/coupons/usage',
    description: 'Get coupon usage statistics',
    authentication: 'admin',
    responseBody: { type: 'CouponUsage[]', description: 'Coupon usage data' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2449,
  },
  {
    method: 'DELETE',
    path: '/api/admin/otp/:phone',
    description: 'Clear OTP for a phone number (for testing)',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2482,
  },
  {
    method: 'GET',
    path: '/api/admin/admins',
    description: 'Get list of all admin users',
    authentication: 'admin',
    responseBody: { type: 'User[]', description: 'Admin users' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2519,
  },
  {
    method: 'POST',
    path: '/api/admin/bootstrap',
    description: 'Bootstrap first admin user',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2546,
  },
  {
    method: 'GET',
    path: '/api/admin/facilitators',
    description: 'Get all group facilitators with their group statistics. Returns facilitators (role=facilitator or role=coach) with recruit counts, active members, and performance metrics.',
    authentication: 'admin',
    responseBody: { type: 'FacilitatorWithStats[]', description: 'Facilitators with group stats including recruitCount, activeCount, and groupPerformance' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6144,
  },
  {
    method: 'GET',
    path: '/api/admin/coaches',
    description: '@deprecated - Use /api/admin/facilitators instead. Legacy endpoint for backwards compatibility.',
    authentication: 'admin',
    responseBody: { type: 'FacilitatorWithStats[]', description: 'Facilitators with group stats (legacy alias)' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6147,
  },
  {
    method: 'POST',
    path: '/api/admin/users/:userId/reassign-group-leader',
    description: 'Reassign a user to a different group leader. Updates the user\'s captainId field, manages recruit indexes, and optionally notifies affected parties. Prevents self-assignment to avoid circular references.',
    authentication: 'admin',
    requestBody: {
      type: 'ReassignGroupLeaderRequest',
      description: 'Reassignment details',
      fields: [
        { name: 'newGroupLeaderId', type: 'string | null', required: true, description: 'New group leader ID (or null to unassign)' },
        { name: 'newCaptainId', type: 'string | null', required: false, description: 'Legacy field - use newGroupLeaderId instead' },
        { name: 'projectId', type: 'string', required: false, description: 'Project context for enrollment updates' },
        { name: 'notify', type: 'boolean', required: false, description: 'Send notification to affected users (default: true)' },
      ],
    },
    responseBody: {
      type: '{ success: boolean, user: User, oldGroupLeader?: User, newGroupLeader?: User }',
      description: 'Updated user with old and new group leader info'
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6590,
  },
  {
    method: 'POST',
    path: '/api/admin/users/:userId/reassign-captain',
    description: '@deprecated - Use /api/admin/users/:userId/reassign-group-leader instead. Legacy endpoint for backwards compatibility.',
    authentication: 'admin',
    requestBody: {
      type: 'ReassignCaptainRequest',
      description: 'Reassignment details (legacy)',
      fields: [
        { name: 'newCaptainId', type: 'string', required: true, description: 'New captain ID' },
        { name: 'notify', type: 'boolean', required: false, description: 'Send notification' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6299,
  },
  {
    method: 'POST',
    path: '/api/admin/users/bulk-reassign-group-leader',
    description: 'Bulk reassign multiple users to a new group leader. Efficiently processes batch reassignments with a single API call. Returns detailed results for each user including success/failure status.',
    authentication: 'admin',
    requestBody: {
      type: 'BulkReassignGroupLeaderRequest',
      description: 'Bulk reassignment request',
      fields: [
        { name: 'userIds', type: 'string[]', required: true, description: 'Array of user IDs to reassign' },
        { name: 'newGroupLeaderId', type: 'string', required: true, description: 'New group leader ID for all users' },
        { name: 'newCaptainId', type: 'string', required: false, description: 'Legacy field - use newGroupLeaderId instead' },
        { name: 'notify', type: 'boolean', required: false, description: 'Send notifications to affected users (default: true)' },
      ],
    },
    responseBody: {
      type: '{ results: Array<{ userId: string, success: boolean, error?: string }>, summary: { total: number, succeeded: number, failed: number } }',
      description: 'Batch results with per-user status and summary counts'
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6430,
  },
  {
    method: 'POST',
    path: '/api/admin/users/bulk-reassign-captain',
    description: '@deprecated - Use /api/admin/users/bulk-reassign-group-leader instead. Legacy endpoint for backwards compatibility.',
    authentication: 'admin',
    requestBody: {
      type: 'BulkReassignRequest',
      description: 'Bulk reassignment (legacy)',
      fields: [
        { name: 'userIds', type: 'string[]', required: true, description: 'Users to reassign' },
        { name: 'newCaptainId', type: 'string', required: true, description: 'New captain ID' },
        { name: 'notify', type: 'boolean', required: false, description: 'Send notifications' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6433,
  },
  {
    method: 'POST',
    path: '/api/admin/repair-team-assignments',
    description: 'Repair broken team assignments - fixes users who were assigned to captains but missing from recruits index',
    authentication: 'admin',
    responseBody: {
      type: '{ repaired: Array<{ userId: string, userName: string, captainId: string, action: string }>, errors: Array<{ userId: string, error: string }>, summary: { totalUsers: number, repairedCount: number, errorCount: number } }',
      description: 'Repair results with detailed breakdown of fixes and any errors'
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6214,
  },

  // ============================================================================
  // PROJECTS
  // ============================================================================
  {
    method: 'GET',
    path: '/api/projects',
    description: 'Get all projects (admin)',
    authentication: 'admin',
    responseBody: { type: 'ResetProject[]', description: 'All projects' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2780,
  },
  {
    method: 'GET',
    path: '/api/projects/open',
    description: 'Get projects open for enrollment',
    authentication: 'none',
    responseBody: { type: 'ResetProject[]', description: 'Open projects' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2794,
  },
  {
    method: 'GET',
    path: '/api/projects/active',
    description: 'Get currently active projects',
    authentication: 'user',
    responseBody: { type: 'ResetProject[]', description: 'Active projects' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2804,
  },
  {
    method: 'GET',
    path: '/api/projects/:projectId',
    description: 'Get specific project details',
    authentication: 'user',
    responseBody: { type: 'ResetProject', description: 'Project details' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2814,
  },
  {
    method: 'POST',
    path: '/api/admin/projects',
    description: 'Create a new project',
    authentication: 'admin',
    requestBody: {
      type: 'CreateProjectRequest',
      description: 'Project details',
      fields: [
        { name: 'name', type: 'string', required: true, description: 'Project name' },
        { name: 'startDate', type: 'string', required: true, description: 'Start date ISO' },
        { name: 'endDate', type: 'string', required: true, description: 'End date ISO' },
        { name: 'enrollmentOpenDate', type: 'string', required: false, description: 'When enrollment opens' },
        { name: 'enrollmentCloseDate', type: 'string', required: false, description: 'When enrollment closes' },
      ],
    },
    responseBody: { type: 'ResetProject', description: 'Created project' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2827,
  },
  {
    method: 'PATCH',
    path: '/api/admin/projects/:projectId',
    description: 'Update project details',
    authentication: 'admin',
    responseBody: { type: 'ResetProject', description: 'Updated project' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2881,
  },
  {
    method: 'DELETE',
    path: '/api/admin/projects/:projectId',
    description: 'Delete a project',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2917,
  },
  {
    method: 'GET',
    path: '/api/admin/projects/:projectId/enrollments',
    description: 'Get all enrollments for a project',
    authentication: 'admin',
    responseBody: { type: 'ProjectEnrollment[]', description: 'Project enrollments' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2948,
  },
  {
    method: 'GET',
    path: '/api/admin/projects/:projectId/cohort-stats',
    description: 'Get cohort statistics for project',
    authentication: 'admin',
    responseBody: { type: 'CohortStats', description: 'Cohort breakdown' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3995,
  },
  {
    method: 'GET',
    path: '/api/projects/:projectId/group',
    description: 'Get group leaderboard for project',
    authentication: 'user',
    responseBody: { type: 'GroupMember[]', description: 'Group leaderboard' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3222,
  },
  {
    method: 'GET',
    path: '/api/projects/:projectId/week',
    description: 'Get current week info for project',
    authentication: 'user',
    responseBody: { type: 'WeekInfo', description: 'Week number and dates' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3256,
  },

  // ============================================================================
  // ENROLLMENTS
  // ============================================================================
  {
    method: 'POST',
    path: '/api/admin/users/:userId/enroll',
    description: 'Admin enroll user in project',
    authentication: 'admin',
    requestBody: {
      type: 'AdminEnrollRequest',
      description: 'Enrollment details',
      fields: [
        { name: 'projectId', type: 'string', required: true, description: 'Project to enroll in' },
        { name: 'cohortType', type: 'string', required: false, description: 'Cohort assignment' },
        { name: 'waivePayment', type: 'boolean', required: false, description: 'Skip payment' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2974,
  },
  {
    method: 'GET',
    path: '/api/admin/users/:userId/enrollments',
    description: 'Get user enrollments (admin)',
    authentication: 'admin',
    responseBody: { type: 'ProjectEnrollment[]', description: 'User enrollments' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3032,
  },
  {
    method: 'DELETE',
    path: '/api/admin/users/:userId/enrollments/:projectId',
    description: 'Remove user from project',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3071,
  },
  {
    method: 'GET',
    path: '/api/enrollments',
    description: 'Get current user enrollments',
    authentication: 'user',
    responseBody: { type: 'ProjectEnrollment[]', description: 'My enrollments' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3106,
  },
  {
    method: 'GET',
    path: '/api/enrollments/:projectId',
    description: 'Get specific enrollment details',
    authentication: 'user',
    responseBody: { type: 'ProjectEnrollment', description: 'Enrollment details' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3133,
  },
  {
    method: 'POST',
    path: '/api/enrollments',
    description: 'Enroll in a project (user initiated)',
    authentication: 'user',
    requestBody: {
      type: 'EnrollRequest',
      description: 'Enrollment request',
      fields: [
        { name: 'projectId', type: 'string', required: true, description: 'Project to enroll in' },
        { name: 'paymentIntentId', type: 'string', required: false, description: 'Stripe payment ID' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3160,
  },
  {
    method: 'PATCH',
    path: '/api/enrollments/:projectId/cohort',
    description: 'Update enrollment cohort (admin)',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3885,
  },
  {
    method: 'PATCH',
    path: '/api/enrollments/:projectId/onboarding',
    description: 'Update onboarding progress',
    authentication: 'user',
    requestBody: {
      type: 'OnboardingUpdate',
      description: 'Onboarding step completion',
      fields: [
        { name: 'step', type: 'string', required: true, description: 'Onboarding step name' },
        { name: 'completed', type: 'boolean', required: true, description: 'Step completed' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3912,
  },
  {
    method: 'PATCH',
    path: '/api/admin/enrollments/:enrollmentId/cohort',
    description: 'Admin update enrollment cohort',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3964,
  },

  // ============================================================================
  // FILE UPLOADS
  // ============================================================================
  {
    method: 'POST',
    path: '/api/upload/presigned-url',
    description: 'Get presigned URL for R2 upload',
    authentication: 'user',
    requestBody: {
      type: 'PresignedUrlRequest',
      description: 'Upload request',
      fields: [
        { name: 'filename', type: 'string', required: true, description: 'File name' },
        { name: 'contentType', type: 'string', required: true, description: 'MIME type' },
        { name: 'purpose', type: 'string', required: false, description: 'avatar|biometric|bug' },
      ],
    },
    responseBody: { type: '{ uploadUrl: string, publicUrl: string }', description: 'Presigned URLs' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3291,
  },
  {
    method: 'POST',
    path: '/api/upload/file',
    description: 'Direct file upload to R2',
    authentication: 'user',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3364,
  },
  {
    method: 'GET',
    path: '/api/media/*',
    description: 'Serve media files from R2',
    authentication: 'none',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3421,
  },
  {
    method: 'POST',
    path: '/api/stream/create-upload',
    description: 'Create Cloudflare Stream upload for video',
    authentication: 'admin',
    responseBody: { type: '{ tusEndpoint: string, apiToken: string }', description: 'TUS upload info' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3453,
  },
  {
    method: 'GET',
    path: '/api/stream/status/:uid',
    description: 'Get Cloudflare Stream video status',
    authentication: 'admin',
    responseBody: { type: 'StreamVideoStatus', description: 'Video processing status' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3503,
  },

  // ============================================================================
  // BUG REPORTS
  // ============================================================================
  {
    method: 'POST',
    path: '/api/bugs',
    description: 'Submit a bug report with optional media',
    authentication: 'user',
    requestBody: {
      type: 'BugReportSubmitRequest',
      description: 'Bug report',
      fields: [
        { name: 'title', type: 'string', required: true, description: 'Brief summary' },
        { name: 'description', type: 'string', required: true, description: 'Detailed description' },
        { name: 'severity', type: 'BugSeverity', required: true, description: 'low|medium|high|critical' },
        { name: 'category', type: 'BugCategory', required: true, description: 'ui|functionality|performance|data|other' },
        { name: 'screenshotUrl', type: 'string', required: false, description: 'Screenshot R2 URL' },
        { name: 'videoUrl', type: 'string', required: false, description: 'Video R2 URL' },
        { name: 'pageUrl', type: 'string', required: true, description: 'Page where bug occurred' },
        { name: 'userAgent', type: 'string', required: true, description: 'Browser info' },
      ],
    },
    responseBody: { type: 'BugReport', description: 'Created bug' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3561,
  },
  {
    method: 'GET',
    path: '/api/bugs/mine',
    description: 'Get my submitted bug reports',
    authentication: 'user',
    responseBody: { type: 'BugReport[]', description: 'My bugs' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3611,
  },
  {
    method: 'GET',
    path: '/api/admin/bugs',
    description: 'Get all bug reports',
    authentication: 'admin',
    responseBody: { type: 'BugReport[]', description: 'All bugs sorted by date' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3624,
  },
  {
    method: 'GET',
    path: '/api/admin/bugs/status/:status',
    description: 'Get bugs filtered by status',
    authentication: 'admin',
    responseBody: { type: 'BugReport[]', description: 'Filtered bugs' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3637,
  },
  {
    method: 'GET',
    path: '/api/admin/bugs/:bugId',
    description: 'Get specific bug report',
    authentication: 'admin',
    responseBody: { type: 'BugReport', description: 'Bug details' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3655,
  },
  {
    method: 'PATCH',
    path: '/api/admin/bugs/:bugId',
    description: 'Update bug status or notes',
    authentication: 'admin',
    requestBody: {
      type: 'BugReportUpdateRequest',
      description: 'Update fields',
      fields: [
        { name: 'status', type: 'BugStatus', required: false, description: 'open|in_progress|resolved|closed' },
        { name: 'adminNotes', type: 'string', required: false, description: 'Internal notes' },
      ],
    },
    responseBody: { type: 'BugReport', description: 'Updated bug' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3672,
  },
  {
    method: 'DELETE',
    path: '/api/admin/bugs/:bugId',
    description: 'Delete a bug report',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3705,
  },
  {
    method: 'POST',
    path: '/api/admin/bugs/:bugId/analyze',
    description: 'Trigger AI analysis of bug',
    authentication: 'admin',
    requestBody: {
      type: 'AnalyzeBugRequest',
      description: 'Analysis options',
      fields: [
        { name: 'includeScreenshot', type: 'boolean', required: false, description: 'Include screenshot in analysis' },
        { name: 'includeVideo', type: 'boolean', required: false, description: 'Include video in analysis' },
      ],
    },
    responseBody: { type: 'BugAIAnalysis', description: 'Analysis result' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3734,
  },
  {
    method: 'GET',
    path: '/api/admin/bugs/:bugId/analysis',
    description: 'Get latest AI analysis for bug',
    authentication: 'admin',
    responseBody: { type: 'BugAIAnalysis | null', description: 'Analysis or null' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3821,
  },
  {
    method: 'GET',
    path: '/api/admin/ai-analyses',
    description: 'Get recent AI analyses',
    authentication: 'admin',
    responseBody: { type: 'BugAIAnalysis[]', description: 'Recent analyses' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3840,
  },

  // ============================================================================
  // SETTINGS
  // ============================================================================
  {
    method: 'GET',
    path: '/api/settings',
    description: 'Get system settings',
    authentication: 'user',
    responseBody: { type: 'SystemSettings', description: 'System settings' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3857,
  },
  {
    method: 'PUT',
    path: '/api/admin/settings',
    description: 'Update system settings',
    authentication: 'admin',
    requestBody: {
      type: 'SystemSettings',
      description: 'Settings to update',
      fields: [
        { name: 'enrollmentOpen', type: 'boolean', required: false, description: 'Allow new enrollments' },
        { name: 'maintenanceMode', type: 'boolean', required: false, description: 'Enable maintenance' },
        { name: 'kitReminderEnabled', type: 'boolean', required: false, description: 'Show kit reminders' },
      ],
    },
    responseBody: { type: 'SystemSettings', description: 'Updated settings' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 3867,
  },
  {
    method: 'PUT',
    path: '/api/admin/settings/points',
    description: 'Update points configuration',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4224,
  },
  {
    method: 'GET',
    path: '/api/settings/points',
    description: 'Get points configuration',
    authentication: 'user',
    responseBody: { type: 'PointsConfig', description: 'Points settings' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4254,
  },

  // ============================================================================
  // GENEALOGY
  // ============================================================================
  {
    method: 'GET',
    path: '/api/genealogy/me',
    description: 'Get current user genealogy tree',
    authentication: 'user',
    responseBody: { type: 'GenealogyNode', description: 'User tree' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4025,
  },
  {
    method: 'GET',
    path: '/api/genealogy/:userId',
    description: 'Get genealogy tree for user',
    authentication: 'user',
    responseBody: { type: 'GenealogyNode', description: 'User tree' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4040,
  },
  {
    method: 'GET',
    path: '/api/admin/genealogy/roots',
    description: 'Get all root coaches (no referrer)',
    authentication: 'admin',
    responseBody: { type: 'GenealogyNode[]', description: 'Root nodes' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4079,
  },
  {
    method: 'GET',
    path: '/api/admin/genealogy/:userId',
    description: 'Get genealogy tree for any user (admin)',
    authentication: 'admin',
    responseBody: { type: 'GenealogyNode', description: 'User tree' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4122,
  },

  // ============================================================================
  // POINTS
  // ============================================================================
  {
    method: 'GET',
    path: '/api/points/history',
    description: 'Get current user points history',
    authentication: 'user',
    responseBody: { type: 'PointsTransaction[]', description: 'Points history' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4142,
  },
  {
    method: 'GET',
    path: '/api/admin/points/:userId/history',
    description: 'Get points history for any user',
    authentication: 'admin',
    responseBody: { type: 'PointsTransaction[]', description: 'User points history' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4155,
  },
  {
    method: 'GET',
    path: '/api/admin/points/recent',
    description: 'Get recent points transactions',
    authentication: 'admin',
    responseBody: { type: 'PointsTransaction[]', description: 'Recent transactions' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4169,
  },
  {
    method: 'POST',
    path: '/api/admin/points/adjust',
    description: 'Manually adjust user points',
    authentication: 'admin',
    requestBody: {
      type: 'AdjustPointsRequest',
      description: 'Adjustment details',
      fields: [
        { name: 'userId', type: 'string', required: true, description: 'User to adjust' },
        { name: 'amount', type: 'number', required: true, description: 'Points to add (negative to subtract)' },
        { name: 'reason', type: 'string', required: true, description: 'Reason for adjustment' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4183,
  },

  // ============================================================================
  // COURSE CONTENT (LMS)
  // ============================================================================
  {
    method: 'GET',
    path: '/api/admin/projects/:projectId/content',
    description: 'Get all content for project (admin)',
    authentication: 'admin',
    responseBody: { type: 'CourseContent[]', description: 'Project content' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4273,
  },
  {
    method: 'GET',
    path: '/api/admin/content/:contentId',
    description: 'Get specific content item',
    authentication: 'admin',
    responseBody: { type: 'CourseContent', description: 'Content details' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4287,
  },
  {
    method: 'POST',
    path: '/api/admin/content',
    description: 'Create new course content',
    authentication: 'admin',
    requestBody: {
      type: 'CreateCourseContentRequest',
      description: 'Content to create',
      fields: [
        { name: 'projectId', type: 'string', required: true, description: 'Project ID' },
        { name: 'dayNumber', type: 'number', required: true, description: 'Day 1-28' },
        { name: 'type', type: 'string', required: true, description: 'video|quiz|article' },
        { name: 'title', type: 'string', required: true, description: 'Content title' },
        { name: 'description', type: 'string', required: false, description: 'Content description' },
        { name: 'videoUrl', type: 'string', required: false, description: 'Cloudflare Stream URL' },
        { name: 'quizQuestions', type: 'QuizQuestion[]', required: false, description: 'Quiz questions' },
      ],
    },
    responseBody: { type: 'CourseContent', description: 'Created content' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4304,
  },
  {
    method: 'PATCH',
    path: '/api/admin/content/:contentId',
    description: 'Update course content',
    authentication: 'admin',
    responseBody: { type: 'CourseContent', description: 'Updated content' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4376,
  },
  {
    method: 'DELETE',
    path: '/api/admin/content/:contentId',
    description: 'Delete course content',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4416,
  },
  {
    method: 'POST',
    path: '/api/admin/projects/:projectId/content/reorder',
    description: 'Reorder content within a day',
    authentication: 'admin',
    requestBody: {
      type: 'ReorderContentRequest',
      description: 'New order',
      fields: [
        { name: 'contentIds', type: 'string[]', required: true, description: 'Ordered content IDs' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4441,
  },
  {
    method: 'POST',
    path: '/api/admin/projects/:sourceProjectId/content/copy/:targetProjectId',
    description: 'Copy content from one project to another',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4469,
  },
  {
    method: 'GET',
    path: '/api/admin/projects/:projectId/content/analytics',
    description: 'Get content engagement analytics',
    authentication: 'admin',
    responseBody: { type: 'ContentAnalytics', description: 'Engagement stats' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4516,
  },

  // ============================================================================
  // COURSE (USER-FACING LMS)
  // ============================================================================
  {
    method: 'GET',
    path: '/api/course/overview',
    description: 'Get course overview with progress',
    authentication: 'user',
    responseBody: { type: 'CourseOverview', description: 'Course progress overview' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4574,
  },
  {
    method: 'GET',
    path: '/api/course/day/:dayNumber',
    description: 'Get content for specific day',
    authentication: 'user',
    responseBody: { type: 'DayContentWithProgress', description: 'Day content and progress' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4657,
  },
  {
    method: 'POST',
    path: '/api/course/video/progress',
    description: 'Update video watch progress',
    authentication: 'user',
    requestBody: {
      type: 'VideoProgressRequest',
      description: 'Progress update',
      fields: [
        { name: 'contentId', type: 'string', required: true, description: 'Video content ID' },
        { name: 'progress', type: 'number', required: true, description: 'Progress 0-100' },
        { name: 'currentTime', type: 'number', required: false, description: 'Playback position' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4750,
  },
  {
    method: 'POST',
    path: '/api/course/video/complete',
    description: 'Mark video as completed',
    authentication: 'user',
    requestBody: {
      type: 'VideoCompleteRequest',
      description: 'Completion',
      fields: [
        { name: 'contentId', type: 'string', required: true, description: 'Video content ID' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4848,
  },
  {
    method: 'POST',
    path: '/api/course/quiz/submit',
    description: 'Submit quiz answers',
    authentication: 'user',
    requestBody: {
      type: 'QuizSubmitRequest',
      description: 'Quiz submission',
      fields: [
        { name: 'contentId', type: 'string', required: true, description: 'Quiz content ID' },
        { name: 'answers', type: 'object', required: true, description: 'Question answers' },
      ],
    },
    responseBody: { type: 'QuizResultResponse', description: 'Quiz results and score' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4915,
  },
  {
    method: 'GET',
    path: '/api/course/progress',
    description: 'Get overall course progress',
    authentication: 'user',
    responseBody: { type: 'UserProgress[]', description: 'All progress records' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5081,
  },
  {
    method: 'GET',
    path: '/api/course/comments/:contentId',
    description: 'Get comments for content',
    authentication: 'user',
    responseBody: { type: 'ContentComment[]', description: 'Content comments' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5106,
  },
  {
    method: 'POST',
    path: '/api/course/comments',
    description: 'Add comment to content',
    authentication: 'user',
    requestBody: {
      type: 'AddCommentRequest',
      description: 'Comment to add',
      fields: [
        { name: 'contentId', type: 'string', required: true, description: 'Content ID' },
        { name: 'text', type: 'string', required: true, description: 'Comment text' },
        { name: 'parentId', type: 'string', required: false, description: 'Parent comment for reply' },
      ],
    },
    responseBody: { type: 'ContentComment', description: 'Created comment' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5123,
  },
  {
    method: 'POST',
    path: '/api/course/comments/like',
    description: 'Like/unlike a comment',
    authentication: 'user',
    requestBody: {
      type: 'LikeCommentRequest',
      description: 'Like toggle',
      fields: [
        { name: 'commentId', type: 'string', required: true, description: 'Comment to like' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5155,
  },
  {
    method: 'POST',
    path: '/api/course/content/like',
    description: 'Like/unlike content',
    authentication: 'user',
    requestBody: {
      type: 'LikeContentRequest',
      description: 'Like toggle',
      fields: [
        { name: 'contentId', type: 'string', required: true, description: 'Content to like' },
      ],
    },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5173,
  },
  {
    method: 'GET',
    path: '/api/course/content/:contentId',
    description: 'Get specific content with progress',
    authentication: 'user',
    responseBody: { type: 'CourseContentWithProgress', description: 'Content and user progress' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5191,
  },

  // ============================================================================
  // NOTIFICATIONS
  // ============================================================================
  {
    method: 'GET',
    path: '/api/notifications',
    description: 'Get user notifications',
    authentication: 'user',
    responseBody: { type: 'Notification[]', description: 'User notifications' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5213,
  },
  {
    method: 'GET',
    path: '/api/notifications/unread-count',
    description: 'Get unread notification count',
    authentication: 'user',
    responseBody: { type: '{ count: number }', description: 'Unread count' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5228,
  },
  {
    method: 'POST',
    path: '/api/notifications/:notificationId/read',
    description: 'Mark notification as read',
    authentication: 'user',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5241,
  },
  {
    method: 'POST',
    path: '/api/notifications/mark-all-read',
    description: 'Mark all notifications as read',
    authentication: 'user',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5263,
  },

  // ============================================================================
  // IMPERSONATION
  // ============================================================================
  {
    method: 'POST',
    path: '/api/admin/impersonate/start',
    description: 'Start impersonating a user',
    authentication: 'admin',
    requestBody: {
      type: 'StartImpersonationRequest',
      description: 'Impersonation request',
      fields: [
        { name: 'targetUserId', type: 'string', required: true, description: 'User to impersonate' },
        { name: 'reason', type: 'string', required: false, description: 'Reason for impersonation' },
      ],
    },
    responseBody: { type: 'ImpersonationSession', description: 'Session with expiry' },
    errorCodes: [
      { code: 404, message: 'Not found', description: 'User does not exist' },
      { code: 403, message: 'Cannot impersonate', description: 'Cannot impersonate admin' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5290,
  },
  {
    method: 'POST',
    path: '/api/admin/impersonate/end',
    description: 'End current impersonation session',
    authentication: 'admin',
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5341,
  },
  {
    method: 'GET',
    path: '/api/admin/impersonate/audit',
    description: 'Get impersonation audit log',
    authentication: 'admin',
    responseBody: { type: 'ImpersonationSession[]', description: 'Recent sessions' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 5359,
  },

  // ============================================================================
  // STRIPE PAYMENT ADMIN (NEW)
  // ============================================================================
  {
    method: 'GET',
    path: '/api/admin/stripe/search',
    description: 'Search Stripe charges with filters (card last4, status, amount)',
    authentication: 'admin',
    requestBody: {
      type: 'query params',
      description: 'Search filters',
      fields: [
        { name: 'limit', type: 'number', required: false, description: 'Max results (default 25, max 100)' },
        { name: 'page', type: 'string', required: false, description: 'Cursor for pagination' },
        { name: 'card_last4', type: 'string', required: false, description: 'Filter by card last 4 digits' },
        { name: 'card_brand', type: 'string', required: false, description: 'Filter by card brand (visa, mastercard, etc)' },
        { name: 'status', type: 'string', required: false, description: 'Filter by charge status' },
        { name: 'min_amount', type: 'number', required: false, description: 'Minimum amount in cents' },
        { name: 'max_amount', type: 'number', required: false, description: 'Maximum amount in cents' },
      ],
    },
    responseBody: { type: '{ data: StripeCharge[], has_more: boolean, next_page: string | null }', description: 'Paginated search results' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2591,
  },
  {
    method: 'POST',
    path: '/api/admin/stripe/unlink',
    description: 'Unlink a Stripe payment from a user account',
    authentication: 'admin',
    requestBody: {
      type: 'UnlinkPaymentRequest',
      description: 'User to unlink payment from',
      fields: [
        { name: 'userId', type: 'string', required: true, description: 'User ID to unlink payment from' },
      ],
    },
    responseBody: { type: '{ message: string, user: { id: string, name: string }, previousPaymentId: string }', description: 'Unlink result' },
    errorCodes: [
      { code: 400, message: 'Missing userId', description: 'userId required' },
      { code: 400, message: 'User does not have a linked payment', description: 'No payment to unlink' },
      { code: 404, message: 'User not found', description: 'User does not exist' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 2929,
  },

  // ============================================================================
  // BUG MESSAGING SYSTEM (NEW)
  // ============================================================================
  {
    method: 'GET',
    path: '/api/bugs/:bugId/messages',
    description: 'Get messages for a bug report thread',
    authentication: 'user',
    responseBody: { type: 'BugMessage[]', description: 'Messages in chronological order' },
    errorCodes: [
      { code: 403, message: 'Access denied', description: 'Must be bug owner or admin' },
      { code: 404, message: 'Bug report not found', description: 'Bug does not exist' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4037,
  },
  {
    method: 'POST',
    path: '/api/bugs/:bugId/messages',
    description: 'Add a message to a bug report thread (triggers push notification)',
    authentication: 'user',
    requestBody: {
      type: 'AddBugMessageRequest',
      description: 'Message to add',
      fields: [
        { name: 'message', type: 'string', required: true, description: 'Message content' },
      ],
    },
    responseBody: { type: 'BugMessage', description: 'Created message' },
    errorCodes: [
      { code: 400, message: 'Message is required', description: 'Empty message' },
      { code: 403, message: 'Access denied', description: 'Must be bug owner or admin' },
      { code: 404, message: 'Bug report not found', description: 'Bug does not exist' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4063,
  },
  {
    method: 'GET',
    path: '/api/bugs/:bugId/satisfaction',
    description: 'Get satisfaction feedback for a resolved bug',
    authentication: 'user',
    responseBody: { type: 'BugSatisfaction | null', description: 'User feedback or null' },
    errorCodes: [
      { code: 403, message: 'Access denied', description: 'Must be bug owner or admin' },
      { code: 404, message: 'Bug report not found', description: 'Bug does not exist' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4151,
  },
  {
    method: 'POST',
    path: '/api/bugs/:bugId/satisfaction',
    description: 'Submit satisfaction feedback after bug resolution',
    authentication: 'user',
    requestBody: {
      type: 'SubmitBugSatisfactionRequest',
      description: 'Satisfaction feedback',
      fields: [
        { name: 'rating', type: "'positive' | 'negative'", required: true, description: 'Thumbs up or down' },
        { name: 'feedback', type: 'string', required: false, description: 'Optional written feedback' },
      ],
    },
    responseBody: { type: 'BugSatisfaction', description: 'Created feedback record' },
    errorCodes: [
      { code: 400, message: 'Valid rating required', description: 'Must be positive or negative' },
      { code: 400, message: 'Bug must be resolved', description: 'Can only rate resolved bugs' },
      { code: 400, message: 'Feedback already submitted', description: 'Cannot submit twice' },
      { code: 403, message: 'Only bug reporter can submit', description: 'Not the bug owner' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4177,
  },
  {
    method: 'GET',
    path: '/api/bugs/:bugId',
    description: 'Get single bug with messages and satisfaction (user sees own, admin sees all)',
    authentication: 'user',
    responseBody: { type: '{ bug: BugReport, messages: BugMessage[], satisfaction: BugSatisfaction | null }', description: 'Full bug details' },
    errorCodes: [
      { code: 403, message: 'Access denied', description: 'Must be bug owner or admin' },
      { code: 404, message: 'Bug report not found', description: 'Bug does not exist' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4242,
  },
  {
    method: 'GET',
    path: '/api/bugs/:bugId/detail',
    description: 'Get bug with messages and satisfaction in one call (alias)',
    authentication: 'user',
    responseBody: { type: '{ bug: BugReport, messages: BugMessage[], satisfaction: BugSatisfaction | null }', description: 'Full bug details' },
    errorCodes: [
      { code: 403, message: 'Access denied', description: 'Must be bug owner or admin' },
      { code: 404, message: 'Bug report not found', description: 'Bug does not exist' },
    ],
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 4244,
  },

  // ============================================================================
  // WEB PUSH NOTIFICATIONS (NEW)
  // ============================================================================
  {
    method: 'GET',
    path: '/api/push/vapid-key',
    description: 'Get VAPID public key for web push subscription',
    authentication: 'none',
    responseBody: { type: '{ publicKey: string }', description: 'VAPID public key' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6198,
  },
  {
    method: 'POST',
    path: '/api/push/subscribe',
    description: 'Subscribe to push notifications',
    authentication: 'user',
    requestBody: {
      type: 'PushSubscribeRequest',
      description: 'Push subscription data',
      fields: [
        { name: 'subscription.endpoint', type: 'string', required: true, description: 'Push service endpoint' },
        { name: 'subscription.keys.p256dh', type: 'string', required: true, description: 'P256DH key' },
        { name: 'subscription.keys.auth', type: 'string', required: true, description: 'Auth secret' },
        { name: 'userAgent', type: 'string', required: false, description: 'Device user agent' },
      ],
    },
    responseBody: { type: '{ success: boolean, subscriptionId: string }', description: 'Subscription result' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6203,
  },
  {
    method: 'POST',
    path: '/api/push/unsubscribe',
    description: 'Unsubscribe from push notifications',
    authentication: 'user',
    requestBody: {
      type: 'PushUnsubscribeRequest',
      description: 'Endpoint to unsubscribe',
      fields: [
        { name: 'endpoint', type: 'string', required: true, description: 'Push endpoint to remove' },
      ],
    },
    responseBody: { type: '{ success: boolean, deleted: boolean }', description: 'Unsubscribe result' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6237,
  },
  {
    method: 'GET',
    path: '/api/push/status',
    description: 'Get user push subscription status',
    authentication: 'user',
    responseBody: { type: '{ subscribed: boolean, subscriptionCount: number, subscriptions: PushSubscriptionInfo[] }', description: 'Subscription status' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6259,
  },
  {
    method: 'POST',
    path: '/api/admin/push/test',
    description: 'Send test push notification to a user',
    authentication: 'admin',
    requestBody: {
      type: 'TestPushRequest',
      description: 'Test notification details',
      fields: [
        { name: 'targetUserId', type: 'string', required: true, description: 'User to send to' },
        { name: 'title', type: 'string', required: true, description: 'Notification title' },
        { name: 'body', type: 'string', required: true, description: 'Notification body' },
        { name: 'url', type: 'string', required: false, description: 'Click URL (default /app)' },
      ],
    },
    responseBody: { type: '{ success: boolean, sent: number, failed: number }', description: 'Send result' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6283,
  },
  {
    method: 'POST',
    path: '/api/push/resubscribe',
    description: 'Handle subscription change from service worker',
    authentication: 'none',
    requestBody: {
      type: 'ResubscribeRequest',
      description: 'Old and new subscription data',
      fields: [
        { name: 'oldEndpoint', type: 'string', required: true, description: 'Previous endpoint' },
        { name: 'newSubscription.endpoint', type: 'string', required: true, description: 'New endpoint' },
        { name: 'newSubscription.keys', type: '{ p256dh: string, auth: string }', required: true, description: 'New keys' },
      ],
    },
    responseBody: { type: '{ success: boolean, subscriptionId: string }', description: 'Resubscribe result' },
    sourceFile: 'worker/user-routes.ts',
    sourceLine: 6320,
  },
];
